// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/attendance": {
    params: {};
  };
  "/marks": {
    params: {};
  };
  "/learning": {
    params: {};
  };
  "/platforms": {
    params: {};
  };
  "/settings": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/attendance" | "/marks" | "/learning" | "/platforms" | "/settings";
  };
  "./components/app/layout.jsx": {
    id: "components/app/layout";
    page: "/" | "/attendance" | "/marks" | "/learning" | "/platforms" | "/settings";
  };
  "./pages/Dashboard.jsx": {
    id: "pages/Dashboard";
    page: "/";
  };
  "./pages/Attendance.jsx": {
    id: "pages/Attendance";
    page: "/attendance";
  };
  "./pages/Marks.jsx": {
    id: "pages/Marks";
    page: "/marks";
  };
  "./pages/Learning.jsx": {
    id: "pages/Learning";
    page: "/learning";
  };
  "./pages/Platforms.jsx": {
    id: "pages/Platforms";
    page: "/platforms";
  };
  "./pages/Settings.jsx": {
    id: "pages/Settings";
    page: "/settings";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.jsx");
  "components/app/layout": typeof import("./src/./components/app/layout.jsx");
  "pages/Dashboard": typeof import("./src/./pages/Dashboard.jsx");
  "pages/Attendance": typeof import("./src/./pages/Attendance.jsx");
  "pages/Marks": typeof import("./src/./pages/Marks.jsx");
  "pages/Learning": typeof import("./src/./pages/Learning.jsx");
  "pages/Platforms": typeof import("./src/./pages/Platforms.jsx");
  "pages/Settings": typeof import("./src/./pages/Settings.jsx");
};